name: api-build

on:
  push:
    paths:
      # files whose changes will trigger a build
      - ".github/workflows/api-build.yml"
      - "api/**"

  workflow_dispatch:

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -la
      - uses: actions/checkout@v4
      - run: pwd && ls -la
        working-directory: api
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: |
          dotnet build
          pwd
        working-directory: ./api
