name: butler

on:
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write

jobs:
  chat:
    if: contains(github.event.comment.body, '/chat')
    runs-on: ubuntu-latest
    steps:
      - name: Print Comment body
        run: echo 'Comment Body = ${{ github.event.comment.body }}'
      - uses: ca-dp/code-butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPEN_API_KEY }}
          cmd: chat
          comment_body: ${{ github.event.comment.body }}
