name: gh

on:
  push:
    paths: ".github/workflows/gh.yml"
    branches: main

  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - run: env | grep GH_TOKEN
      - run: gh --version
      - run: gh repo list
      - run: gh issue list
      - run: gh issue list
      - run: gh workflow list
      - run: gh api /repos/:owner/:repo/actions/workflows
